version: '3.8'
services:
  employee-spring-app:
    container_name: EMPLOYEE-SPRING-APP
    build: .
    image: 22cun2/employee-spring-app
    environment:
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    ports:
      - "80:8080"
      - "443:8080"
    restart: always